### ISSUE TITLE
断点上传返回地址错误

### ISSUE THREAD

**Issue by ukid** [sjqzhang/go-fastdfs#55]
在使用TUS断点上传时返回地址没有端口
````
位置TusClient.createUpload
String urlStr = connection.getHeaderField("Location");
````

docker-compose.yml
````
version: "3.7"

services:
  fastdfs0:
    container_name: fastdfs0
    image: sjqzhang/go-fastdfs
    volumes:
      - ./data0:/data
    environment:
      GO_FASTDFS_DIR: /data
    networks:
      fastdfs:
        ipv4_address: 172.30.0.2

  fastdfs1:
    container_name: fastdfs1
    image: sjqzhang/go-fastdfs
    volumes:
      - ./data1:/data
    environment:
      GO_FASTDFS_DIR: /data
    networks:
      fastdfs:
        ipv4_address: 172.30.0.3

  fastdfs2:
    container_name: fastdfs2
    image: sjqzhang/go-fastdfs
    volumes:
      - ./data2:/data
    environment:
      GO_FASTDFS_DIR: /data
    networks:
      fastdfs:
        ipv4_address: 172.30.0.4

  fastdfs-nginx:
    container_name: fastdfs-nginx
    image: nginx
    volumes:
     - ./nginx:/etc/nginx/conf.d
    depends_on:
     - fastdfs0
     - fastdfs1
     - fastdfs2
    networks:
      fastdfs:
        ipv4_address: 172.30.0.250
    ports:
     - "8080:80"

networks:
  fastdfs:
     driver: bridge
     ipam:
       driver: default
       config:
         - subnet: 172.30.0.0/16
````

nginx default.conf
````
upstream group1{
  server 172.30.0.2:8080;
  server 172.30.0.3:8080;
  server 172.30.0.4:8080;
  ip_hash;
}

log_format  upstream  '$remote_addr - $remote_user [$time_local] "$request" '
            '$status $body_bytes_sent "$http_referer" '
            '"$http_user_agent" "$http_x_forwarded_for" '
            '$upstream_addr $request_time $upstream_response_time ';

client_max_body_size 100M;

server {
    listen       80;
    server_name  localhost;

    #charset koi8-r;
    access_log  /var/log/nginx/access.log  upstream;

    location /{
      proxy_set_header    Host $host;
      proxy_set_header    X-Real-IP $remote_addr;
      proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;

      proxy_pass http://group1;
    }

    location /group1{
      proxy_set_header    Host $host;
      proxy_set_header    X-Real-IP $remote_addr;
      proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;

      proxy_pass http://group1;
    }

    #location / {
    #    root   /usr/share/nginx/html;
    #    index  index.html index.htm;
    #}

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    #location ~ \.php$ {
    #    root           html;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #    include        fastcgi_params;
    #}

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}

````
